export const actions = {
    GET_AMBULANCE_REQUEST: "GET_AMBULANCE_REQUEST",
    GET_AMBULANCE_SUCCESS: "GET_AMBULANCE_SUCCESS",
    GET_AMBULANCE_FAILURE: "GET_AMBULANCE_FAILURE",
    GET_DRIVER_REQUEST: "GET_DRIVER_REQUEST",
    GET_DRIVER_SUCCESS: "GET_DRIVER_SUCCESS",
    GET_DRIVER_FAILURE: "GET_DRIVER_FAILURE",
}