export const actions = {
    UPDATE_FORM: "UPDATE_FORM",
    SUBMIT_FORM_REQUEST: "SUBMIT_FORM_REQUEST",
    SUBMIT_FORM_SUCCESS: "SUBMIT_FORM_SUCCESS",
    SUBMIT_FORM_FAILURE: "SUBMIT_FORM_FAILURE"
}
